language: python
cache: pip
sudo: false

python:
 - pypy3
 - 3.6
 - 3.5
 - 3.4

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
 - pip install -U pip
 - pip install -Ur requirements.txt
 - wget https://raw.githubusercontent.com/hugovk/word-tools/master/word_tools.py
 - pip install -U flake8

script:
 - nosetests
 - python wordnik_comment_scraper.py -h
 - python wordnik_list_downloader.py -h
 - python wordnik_list_scraper.py -h
 - flake8 --statistics --count .

matrix:
  fast_finish: true
