language: python
cache: pip
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
 - pip install -U pip
 - pip install -Ur requirements.txt
 - wget https://raw.githubusercontent.com/hugovk/word-tools/master/word_tools.py
 - pip install -U black flake8

script:
 - nosetests
 - python wordnik_comment_scraper.py -h
 - python wordnik_list_downloader.py -h
 - python wordnik_list_scraper.py -h

 # Static analyis
 - rm word_tools.py # Don't analyse the external file
 - flake8 --statistics --count .
 - black --check --diff .
