language: python

python:
 - pypy
 - pypy3
 - 3.5
 - 2.7
 - 3.4
 - 3.3
 - 3.2
 - 2.6

sudo: false

install:
 - pip install -r requirements.txt
 - wget https://raw.githubusercontent.com/hugovk/word-tools/master/word_tools.py
 - pip install pep8 pyflakes

script:
 - nosetests
 - pep8 --statistics --count .
 - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
